-- faces table

create table faces (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    gender TEXT NOT NULL,
    age TEXT NOT NULL
);

INSERT into faces (gender, age)
values
    ('female', 'middle'),
    ('female', 'middle'),
    ('female', 'young'),
    ('female', 'middle'),
    ('male', 'middle'),
    ('female', 'middle'),
    ('female', 'young'),
    ('female', 'middle'),
    ('male', 'middle'),
    ('male', 'young'),
    ('male', 'middle'),
    ('male', 'middle'),
    ('male', 'young'),
    ('female', 'young'),
    ('male', 'middle'),
    ('male', 'middle'),
    ('female', 'middle'),
    ('female', 'middle'),
    ('male', 'middle'),
    ('female', 'middle'),
    ('male', 'old'),
    ('female', 'middle'),
    ('male', 'middle'),
    ('male', 'middle'),
    ('female', 'middle');
